[window]
opacity = 0.95
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10
# transparent_background_colors = true
# draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

# Alacritty Configuration File

[colors]
  # Primary colors
  [colors.primary]
  foreground = "#c4c4b5"  # Light text color
  background = "#191919"  # Very dark background

  # Normal colors
  [colors.normal]
  black   = "#191919"  # Dark background (black)
  red     = "#f3005f"  # Bright red
  green   = "#97e023"  # Light green
  yellow  = "#fa8419"  # Orange/yellow
  blue    = "#9c64fe"  # Purple-blue
  magenta = "#f3005f"  # Bright red (same as normal red)
  cyan    = "#57d1ea"  # Light cyan
  white   = "#c4c4b5"  # Light gray (same as foreground)

  # Bright colors
  [colors.bright]
  black   = "#615e4b"  # Light brownish-gray (bright black)
  red     = "#f3005f"  # Bright red (same as normal red)
  green   = "#97e023"  # Bright green (same as normal green)
  yellow  = "#dfd561"  # Yellowish light brown (bright yellow)
  blue    = "#9c64fe"  # Bright purple-blue (same as normal blue)
  magenta = "#f3005f"  # Bright red (same as normal red)
  cyan    = "#57d1ea"  # Bright cyan (same as normal cyan)
  white   = "#f6f6ee"  # Very light off-white (bright white)

  # Selection colors
  [colors.selection]
  text = "#191919"  # Dark text color for selected text
  background = "#343434"  # Darker background for selection

  # Search match colors
  [colors.search]
  matches = { foreground = "#191919", background = "#f3005f" }  # Red background for search matches
  focused_match = { foreground = "#191919", background = "#dfd561" }  # Light yellow background for focused match

  # Hint colors
  [colors.hints]
  start = { foreground = "#191919", background = "#dfd561" }  # Hint start (light yellow background)
  end = { foreground = "#191919", background = "#f3005f" }  # Hint end (bright red background)

  # Line indicator colors
  [colors.line_indicator]
  foreground = "None"
  background = "None"

  # Footer bar colors
  [colors.footer_bar]
  foreground = "#191919"
  background = "#c4c4b5"


